package org.drools.workshop;
import org.drools.workshop.model.*;

rule "Category By Age: Adult"
    when
        $u: User( age >= 18, category == null ||  == "")
    then
        $u.setCategory("Adult");
end

rule "Category By Age: Teenager"
    when
        $u: User( age >= 12 && < 18, category == null || == "")
    then
        $u.setCategory("Teenager");
end

rule "Category By Age: Children"
    when
        $u: User( age < 12 && >= 0, category == null || == "")
    then
        $u.setCategory("Children");
end

rule "Category By Age: Not Valid"
    when
        $u: User( age < 0, category == null || == "")
    then
        $u.setCategory("Not Valid");
end

rule "hermano"
     when
	$pa1 : Padre()
	$pa2 : Padre($pa1.padre == padre && $pa1.hijo != hijo)
     then
	insert(new Hermano($pa1.getHijo(), $pa2.getHijo()));
end

rule "ancestro1"
    when
        $p : Padre()
    then
        insert(new Ancestro($p.getPadre(), $p.getHijo())); //el ancestro mas directo, es mi propio padre. 
end

rule "ancestro2"
    when 
        $p : Padre()
        $a : Ancestro($p.hijo == ancestro)
    then
        insert(new Ancestro($p.getPadre(), $a.getDescendiente()));
end

rule "abuelo"
    when
        $p : Padre() //es el abuelo
        $p1 : Padre($p.hijo == padre, $p.padre != hijo ) //es el nieto
      //  eval($p.getHijo() == $p1.getPadre())
    then
        insert(new Abuelo($p.getPadre(), $p1.getHijo()));
end
